# Format: joint_name: [x, y, z] where xyz defines the axis direction
joint_axes:
  joint0: [0, 0, 1]
  joint1: [0, 0, 1]
  joint2: [0, 0, 1]
  joint3: [0, 0, 1]
  joint4: [0, 0, 1]
  joint5: [0, 0, 1]
  joint6: [0, 0, 1]
